# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12da7ede5d6456f771aa66ed1806de07b7e1b1873bb5085117e896ba6eaf21baf1d5277ce0c41d146ec90e73504f2130ec60ca5e1995aaac37b1e47c44075533

test:
  secret_key_base: 5027ff9c7e6bbcea9adc3ca8ea0b97305abaea365f9136886acef081c36405d548469470a91dea047092c045d1bef78f7f85b403fc638b1c7000107c15c76660

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
